import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(process.cwd(), ".env.local") });

import mongoose from "mongoose";
import connectDB from "../connect";
import Skill from "../models/Skill";

const skills = [
  // --- Frontend (Circle) ---
  {
    name: "React",
    icon: "SiReact",
    icon_group: "si",
    icon_type: "icon",
    description: "Component-based UI library",
    group: "frontend",
    is_top_skill: true,
    order: 1,
    color: "#61DAFB",
  },
  {
    name: "Next.js",
    icon: "SiNextdotjs",
    icon_group: "si",
    icon_type: "icon",
    description: "React framework for production",
    group: "frontend",
    is_top_skill: true,
    order: 2,
    color: "#000000",
  },
  {
    name: "TypeScript",
    icon: "SiTypescript",
    icon_group: "si",
    icon_type: "icon",
    description: "Typed JavaScript for scale",
    group: "frontend",
    is_top_skill: true,
    order: 3,
    color: "#3178C6",
  },
  {
    name: "Tailwind CSS",
    icon: "SiTailwindcss",
    icon_group: "si",
    icon_type: "icon",
    description: "Utility-first CSS framework",
    group: "frontend",
    is_top_skill: false,
    order: 4,
    color: "#06B6D4",
  },
  {
    name: "Framer Motion",
    icon: "SiFramer",
    icon_group: "si",
    icon_type: "icon",
    description: "Production-ready motion library",
    group: "frontend",
    is_top_skill: false,
    order: 5,
    color: "#0055FF",
  },
  {
    name: "Redux",
    icon: "SiRedux",
    icon_group: "si",
    icon_type: "icon",
    description: "State management container",
    group: "frontend",
    is_top_skill: false,
    order: 6,
    color: "#764ABC",
  },
  {
    name: "HTML5",
    icon: "SiHtml5",
    icon_group: "si",
    icon_type: "icon",
    description: "Core web structure",
    group: "frontend",
    is_top_skill: false,
    order: 7,
    color: "#E34F26",
  },
  {
    name: "CSS3",
    icon: "SiCss",
    icon_group: "si",
    icon_type: "icon",
    description: "Advanced styling",
    group: "frontend",
    is_top_skill: false,
    order: 8,
    color: "#1572B6",
  },
  {
    name: "JavaScript",
    icon: "SiJavascript",
    icon_group: "si",
    icon_type: "icon",
    description: "Dynamic scripting",
    group: "frontend",
    is_top_skill: true,
    order: 9,
    color: "#F7DF1E",
  },
  {
    name: "Vite",
    icon: "SiVite",
    icon_group: "si",
    icon_type: "icon",
    description: "Fast frontend tooling",
    group: "frontend",
    is_top_skill: false,
    order: 10,
    color: "#646CFF",
  },
  {
    name: "Figma",
    icon: "SiFigma",
    icon_group: "si",
    icon_type: "icon",
    description: "Interface design tool",
    group: "frontend",
    is_top_skill: false,
    order: 11,
    color: "#F24E1E",
  },
  {
    name: "Storybook",
    icon: "SiStorybook",
    icon_group: "si",
    icon_type: "icon",
    description: "UI component explorer",
    group: "frontend",
    is_top_skill: false,
    order: 12,
    color: "#FF4785",
  },

  // --- Backend (Triangle) ---
  {
    name: "Node.js",
    icon: "SiNodedotjs",
    icon_group: "si",
    icon_type: "icon",
    description: "JavaScript runtime",
    group: "backend",
    is_top_skill: true,
    order: 13,
    color: "#339933",
  },
  {
    name: "Python",
    icon: "SiPython",
    icon_group: "si",
    icon_type: "icon",
    description: "Versatile programming",
    group: "backend",
    is_top_skill: true,
    order: 14,
    color: "#3776AB",
  },
  {
    name: "Django",
    icon: "SiDjango",
    icon_group: "si",
    icon_type: "icon",
    description: "High-level Python framework",
    group: "backend",
    is_top_skill: true,
    order: 15,
    color: "#092E20",
  },
  {
    name: "FastAPI",
    icon: "SiFastapi",
    icon_group: "si",
    icon_type: "icon",
    description: "Modern Python API framework",
    group: "backend",
    is_top_skill: true,
    order: 16,
    color: "#05998B",
  },
  {
    name: "PostgreSQL",
    icon: "SiPostgresql",
    icon_group: "si",
    icon_type: "icon",
    description: "Advanced relational DB",
    group: "backend",
    is_top_skill: true,
    order: 17,
    color: "#4169E1",
  },
  {
    name: "MongoDB",
    icon: "SiMongodb",
    icon_group: "si",
    icon_type: "icon",
    description: "NoSQL document database",
    group: "backend",
    is_top_skill: false,
    order: 18,
    color: "#47A248",
  },
  {
    name: "Redis",
    icon: "SiRedis",
    icon_group: "si",
    icon_type: "icon",
    description: "In-memory data store",
    group: "backend",
    is_top_skill: false,
    order: 19,
    color: "#DC382D",
  },
  {
    name: "Go",
    icon: "SiGo",
    icon_group: "si",
    icon_type: "icon",
    description: "Concurrent systems language",
    group: "backend",
    is_top_skill: false,
    order: 20,
    color: "#00ADD8",
  },
  {
    name: "Express",
    icon: "SiExpress",
    icon_group: "si",
    icon_type: "icon",
    description: "Fast, unopinionated Node framework",
    group: "backend",
    is_top_skill: false,
    order: 21,
    color: "#000000",
  },
  {
    name: "Prisma",
    icon: "SiPrisma",
    icon_group: "si",
    icon_type: "icon",
    description: "Next-gen ORM",
    group: "backend",
    is_top_skill: false,
    order: 22,
    color: "#2D3748",
  },
  {
    name: "GraphQL",
    icon: "SiGraphql",
    icon_group: "si",
    icon_type: "icon",
    description: "Query language for APIs",
    group: "backend",
    is_top_skill: false,
    order: 23,
    color: "#E10098",
  },
  {
    name: "Drizzle",
    icon: "Drizzle",
    icon_group: "text",
    icon_type: "text",
    description: "Typescript ORM",
    group: "backend",
    is_top_skill: false,
    order: 24,
    color: "#C5F74F",
  },

  // --- DevOps (Square) ---
  {
    name: "Docker",
    icon: "SiDocker",
    icon_group: "si",
    icon_type: "icon",
    description: "Containerization platform",
    group: "devops",
    is_top_skill: true,
    order: 25,
    color: "#2496ED",
  },
  {
    name: "Kubernetes",
    icon: "SiKubernetes",
    icon_group: "si",
    icon_type: "icon",
    description: "Container orchestration",
    group: "devops",
    is_top_skill: false,
    order: 26,
    color: "#326CE5",
  },
  {
    name: "AWS",
    icon: "FaAws",
    icon_group: "fa",
    icon_type: "icon",
    description: "Cloud infrastructure",
    group: "devops",
    is_top_skill: true,
    order: 27,
    color: "#FF9900",
  },
  {
    name: "Git",
    icon: "SiGit",
    icon_group: "si",
    icon_type: "icon",
    description: "Version control",
    group: "devops",
    is_top_skill: false,
    order: 28,
    color: "#F05032",
  },
  {
    name: "GitHub Actions",
    icon: "SiGithubactions",
    icon_group: "si",
    icon_type: "icon",
    description: "CI/CD automation",
    group: "devops",
    is_top_skill: false,
    order: 29,
    color: "#2088FF",
  },
  {
    name: "Terraform",
    icon: "SiTerraform",
    icon_group: "si",
    icon_type: "icon",
    description: "Infrastructure as code",
    group: "devops",
    is_top_skill: false,
    order: 30,
    color: "#7B42BC",
  },
  {
    name: "Linux",
    icon: "SiLinux",
    icon_group: "si",
    icon_type: "icon",
    description: "Open source OS",
    group: "devops",
    is_top_skill: false,
    order: 31,
    color: "#FCC624",
  },
  {
    name: "Nginx",
    icon: "SiNginx",
    icon_group: "si",
    icon_type: "icon",
    description: "Web server & proxy",
    group: "devops",
    is_top_skill: false,
    order: 32,
    color: "#009639",
  },
  {
    name: "Azure",
    icon: "VscAzure",
    icon_group: "vsc",
    icon_type: "icon",
    description: "Microsoft cloud",
    group: "devops",
    is_top_skill: false,
    order: 33,
    color: "#0078D4",
  },
  {
    name: "Jenkins",
    icon: "SiJenkins",
    icon_group: "si",
    icon_type: "icon",
    description: "Automation server",
    group: "devops",
    is_top_skill: false,
    order: 34,
    color: "#D24939",
  },

  // --- Database (Ticker) ---
  {
    name: "SQLite",
    icon: "SiSqlite",
    icon_group: "si",
    icon_type: "icon",
    description: "Lightweight SQL",
    group: "database",
    is_top_skill: false,
    order: 35,
    color: "#003B57",
  },
  {
    name: "Elasticsearch",
    icon: "SiElasticsearch",
    icon_group: "si",
    icon_type: "icon",
    description: "Search & analytics engine",
    group: "database",
    is_top_skill: false,
    order: 36,
    color: "#005571",
  },

  // --- Tools (Ticker) ---
  {
    name: "VS Code",
    icon: "SiVisualstudiocode",
    icon_group: "si",
    icon_type: "icon",
    description: "Code editor",
    group: "tools",
    is_top_skill: false,
    order: 37,
    color: "#007ACC",
  },
  {
    name: "Postman",
    icon: "SiPostman",
    icon_group: "si",
    icon_type: "icon",
    description: "API platform",
    group: "tools",
    is_top_skill: false,
    order: 38,
    color: "#FF6C37",
  },
];

async function seed() {
  try {
    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) throw new Error("MONGODB_URI is not defined");

    await mongoose.connect(mongoUri);
    console.log("Connected to MongoDB for seeding skills.");

    await Skill.deleteMany({});
    console.log("Cleared existing skills.");

    await Skill.insertMany(skills);
    console.log(`Successfully seeded ${skills.length} skills.`);

    process.exit(0);
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
}

seed();
